export type tutsDataType = {
  title: string;
  id: number;
  img: string;
  author: string;
  category: string;
  tags: string[];
  source: string;
  view: number;
  featured?: false;
  hidden?: false;
  description?: string;
  url: string;
  date: string;
};

// see public folder for thumbnail and logos
// TODO: automate fetching downloads
export const tutsData: tutsDataType[] = [
  {
    id: 10,
    title: "Halftone Effect",
    img: "halftone-effect.png",
    date: "18 Sep, 2022",
    description: `Yes, this is @figma . Simple halftone effects can be easily added to your photos and illustrations to give them a retro look. Another experimenting with @rogie NT plugin.`,
    author: "realvjy",
    tags: ["figma", "video"],
    view: 51000,
    hidden: false,
    category: "figma",
    url: "https://x.com/realvjy/status/1571479068851466240",
    source: "twitter",
  },
  {
    id: 11,
    title: "Engrave Effect",
    img: "engrave-effect.png",
    date: "27 Sep, 2022",
    description: `Experiment #9845 with @rogie NT plugin in @figma 😍. Creating the look of an old engraving halftone print was the challenge. Guess what, it's very simple to create by just using some wave patterns and blending modes.`,
    author: "realvjy",
    tags: ["figma", "video"],
    view: 51000,
    hidden: false,
    category: "figma",
    url: "https://x.com/realvjy/status/1574735646140162048",
    source: "twitter",
  },
  {
    id: 14,
    title: "Holographic Look",
    img: "holographic.png",
    date: "22 Sep, 2022",
    description: `Here's another experiment with @rogie NT plugin in @figma . I was trying to replicate the look of frosted glass using a special noise option hidden in the plugin. But, when I meshed up the colors together, it gave an interesting holographic look`,
    author: "realvjy",
    tags: ["figma", "video"],
    view: 51000,
    hidden: false,
    category: "figma",
    url: "https://x.com/realvjy/status/1572929708731559937",
    source: "twitter",
  },

  {
    id: 15,
    title: "Effect with NT plugin",
    img: "effect-with-nt.png",
    date: "21 Nov, 2022",
    description: `Collection of effect using NT plugin`,
    author: "realvjy",
    tags: ["figma"],
    view: 51000,
    hidden: false,
    category: "figma",
    url: "https://www.figma.com/community/file/1176491955948168493/noise-and-effects-with-nt-plugin",
    source: "figma",
  },
  {
    id: 16,
    title: "Why I love Figma?",
    img: "love-figma.jpeg",
    date: "18 Oct, 2023",
    description: `Why I love @figma ? Every time I use Figma to create illustrations, you guys always ask me why. Here are a few points I would like to share in this thread 🧶. I also uploaded a time lapse to YouTube ▶️`,
    author: "realvjy",
    tags: ["figma", "sketch", "penpot"],
    view: 51000,
    hidden: false,
    category: "figma",
    url: "https://x.com/realvjy/status/1582359449963966464",
    source: "twitter",
  },
  {
    id: 17,
    title: "A Cool Loader",
    img: "cool-loader.jpeg",
    date: "6 Jan, 2023",
    description: `Small tips for creating this cool loader quickly in figma`,
    author: "realvjy",
    tags: ["figma", "any"],
    view: 51000,
    hidden: false,
    category: "figma",
    url: "https://x.com/realvjy/status/1611352724968452098",
    source: "twitter",
  },

  {
    id: 18,
    title: "Leaf Loader",
    img: "leaf-loader.gif",
    date: "9 Jan, 2023",
    description: `Loading experiment continued. Over the weekend created this cool looking loading animation in @figma . Small tutorial video and behind the scene 🧶`,
    author: "realvjy",
    tags: ["figma"],
    view: 51000,
    hidden: false,
    category: "figma",
    url: "https://x.com/realvjy/status/1612408016313389057",
    source: "twitter",
  },
  {
    id: 29,
    title: "Head Rig",
    img: "head-rig.png",
    date: "1 Nov, 2022",
    description: `Another fun experiment using @figma prototype. I made this small head rig last week. Creating this was lot of fun 😍. By using cavas as masks and combining with autolayout, I created this so quickly.`,
    author: "realvjy",
    tags: ["figma", "video"],
    view: 51000,
    hidden: false,
    category: "figma",
    url: "https://x.com/realvjy/status/1587420082036412417",
    source: "twitter",
  },
  {
    id: 30,
    title: "Figbruary 2023 - realvjy",
    img: "figbruary-2023.png",
    date: "17 March, 2023",
    description: `From creating simple illustration to animation and faking 3D rocket in the space. Sharing all 28 @figma experiments from the figbruary.com 2023 challenge.`,
    author: "realvjy",
    tags: ["figma"],
    view: 51000,
    hidden: false,
    category: "figma",
    url: "https://www.figma.com/community/file/1218524169091357244",
    source: "figma",
  },
  {
    id: 33,
    title: "Figma Emoji",
    img: "figma-emoji.jpeg",
    date: "14 Nov, 2023",
    description: `I found that if you use drop shadow or inner shadow on any layer, the limit is 8. In spite of this, it is enough to make any shape like 3D. One secret shared below ☺️.`,
    author: "realvjy",
    tags: ["figma"],
    view: 51000,
    hidden: false,
    category: "figma",
    url: "https://x.com/realvjy/status/1592117127716417537",
    source: "twitter",
  },
  {
    id: 36,
    title: "Isometric City",
    img: "isometric-city.png",
    date: "4 Apr, 2023",
    description: `Creating an isometric city landscape by setting up isometric shapes as component in @figma . When I update the base component, the isometric shapes update smoothly😍. Here small demo...`,
    author: "realvjy",
    tags: ["figma", "video"],
    view: 51000,
    hidden: false,
    category: "figma",
    url: "https://x.com/realvjy/status/1643231924293443586",
    source: "twitter",
  },
  {
    id: 38,
    title: "Figma Gold",
    img: "figma-gold.jpeg",
    date: "16 Jun, 2023",
    description: `For creating metal, I always use layer blur instead of gradient. And here is a cheat sheet to create a cool-looking gold in @figma ✨`,
    author: "realvjy",
    tags: ["figma", "any"],
    view: 51000,
    hidden: false,
    category: "figma",
    url: "https://x.com/realvjy/status/1669672486559002624",
    source: "twitter",
  },
  {
    id: 43,
    title: "Smooth Gradient",
    img: "smooth-gradient.jpeg",
    date: "9 Dec, 2022",
    description: `Small tip about blending gradients in @figma with background blur. You can create cool iridescent gradients using it.`,
    author: "realvjy",
    tags: ["figma"],
    view: 51000,
    hidden: false,
    category: "figma",
    url: "https://x.com/realvjy/status/1601209853875458053",
    source: "twitter",
  },
  {
    id: 49,
    title: "Cool Loader using Figma Variable",
    img: "loader-figma-variable.png",
    date: "7 Jul, 2023",
    description: `Here quick @figma tutorials on how to create a functional loader with variable and conditions 🤩. Small video tutorials added. And get the code cheatsheet and more from here`,
    author: "realvjy",
    tags: ["figma", "video"],
    view: 51000,
    hidden: false,
    category: "figma",
    url: "https://x.com/realvjy/status/1677281849431793664",
    source: "twitter",
  },
  {
    id: 51,
    title: "Crystal Fake 3D rotation",
    img: "crystal-s.gif",
    date: "24 May, 2024",
    description: `Lil experiment and demo to fake 3d in @figma ✨ Just few polygons, masking and smart components`,
    author: "realvjy",
    tags: ["figma"],
    view: 51000,
    hidden: false,
    category: "figma",
    url: "https://x.com/realvjy/status/1793976265449587099",
    source: "twitter",
  },
  {
    id: 54,
    title: "Figma Variable Experiment to create Segment Control",
    img: "segment-control-variable.png",
    date: "27 Dec, 2023",
    description: `It’s @figma fun day - Here's a quick tutorial demo for smart use case of the new variable updates. Created a smart segment control button and it’s so intelligent. Also shared cheatsheet for all variables below.`,
    author: "realvjy",
    tags: ["figma", "video"],
    view: 51000,
    hidden: false,
    category: "figma",
    url: "https://x.com/realvjy/status/1733104300354646473",
    source: "twitter",
  },
  {
    id: 55,
    title: "Speech visualization animation",
    img: "ai-animation.png",
    date: "7 Feb, 2024",
    description: `Created this animation for speech visualization in Figma for #figbruary. It's a very simple animation. I also created a short video tutorial for the same. More assets shared below. Enjoy`,
    author: "realvjy",
    tags: ["figma", "video"],
    view: 51000,
    hidden: false,
    category: "figma",
    url: "https://x.com/realvjy/status/1755252069718446315",
    source: "twitter",
  },
  {
    id: 57,
    title: "Create Hex Grid",
    img: "hex-grid-cheatsheet.jpeg",
    date: "27 Dec, 2023",
    description: `I was creating a layout for a game idea and looking for an easier way to generate a hex grid in @figma . After experimenting, found the exact values and tricks using smart components and auto layout to solve it. Added a quick tutorial video and demo here. Enjoy 🤩`,
    author: "realvjy",
    tags: ["figma", "video"],
    view: 51000,
    hidden: false,
    category: "figma",
    url: "https://x.com/realvjy/status/1739973126270885973",
    source: "twitter",
  },
  {
    id: 57,
    title: "Typography & Gradients Variable",
    img: "typography-gradient.png",
    date: "18 April, 2024",
    description: `Created this quick demo for Typography & Gradients Variable in @figma 😻. Also sharing small video tutorial. Variable cheatsheet below. Enjoy!`,
    author: "realvjy",
    tags: ["figma", "video"],
    view: 51000,
    hidden: false,
    category: "figma",
    url: "https://x.com/realvjy/status/1780935796507247046",
    source: "twitter",
  },
  {
    id: 61,
    title: "Juice glass animation with figma Variable",
    img: "juice-glass.png",
    date: "19 June, 2023",
    description: `Another quick @figma tutorial to create this animation using variable and conditions 🥤.  Small video to create this included. And get the code cheatsheet shared below. ✨`,
    author: "realvjy",
    tags: ["figma", "video"],
    view: 51000,
    hidden: false,
    category: "figma",
    url: "https://x.com/realvjy/status/1808854859371733261",
    source: "twitter",
  },

  {
    id: 65,
    title: "Cool Loaders - Prototypes",
    img: "cool-loaders.png",
    date: "7 Feb, 2024",
    description: `Collection of some cool loaders prototype`,
    author: "realvjy",
    tags: ["figma", "video"],
    view: 51000,
    hidden: false,
    category: "figma",
    url: "https://www.figma.com/community/file/1318911304163997047",
    source: "figma",
  },
  {
    id: 85,
    title: "Moving Sphere",
    img: "moving-sphere.gif",
    date: "25 April, 2024",
    description: `Moving sphere experiment in @figma ✨`,
    author: "realvjy",
    tags: ["figma"],
    view: 51000,
    hidden: false,
    category: "figma",
    url: "https://x.com/realvjy/status/1783474209089319303",
    source: "twitter",
  },
  {
    id: 80,
    title: "Modular Illustration",
    img: "modular-ticket-illustration.gif",
    date: "14 May, 2024",
    description: `Quick experment and demo in @figma : A non-destructive workflow to create modular illustrations or design ✨`,
    author: "realvjy",
    tags: ["figma"],
    view: 51000,
    hidden: false,
    category: "figma",
    url: "https://x.com/realvjy/status/1790353490071507013",
    source: "twitter",
  },
  {
    id: 90,
    title: "Figma Variable & Animation #2",
    img: "figma-illustration-live-1.png",
    date: "14 Jun, 2024",
    description: `3 hours long stream on youtube to create figma illustration of charcter from inside out movie. Also shared lot's of tips and tricks.`,
    author: "realvjy",
    tags: ["figma", "video"],
    view: 51000,
    hidden: false,
    category: "figma",
    url: "https://www.youtube.com/watch?v=ly3EUIZaETQ",
    source: "youtube",
  },
  {
    id: 91,
    title: "Glow Effect",
    img: "glow-cheatsheet.gif",
    date: "24 June, 2024",
    description: `Steps to create glow effect in figma`,
    author: "realvjy",
    tags: ["figma", "any"],
    view: 51000,
    hidden: false,
    category: "figma",
    url: "https://x.com/realvjy/status/1805220290382717219",
    source: "twitter",
  },
  {
    id: 114,
    title: "Create Shiny Metal",
    img: "shiny-metal.jpeg",
    date: "4 Jul, 2024",
    description: `Let's qucikly create some realstic and shiny metal @figma✨`,
    author: "realvjy",
    tags: ["figma", "any"],
    view: 51000,
    hidden: false,
    category: "figma",
    url: "https://x.com/realvjy/status/1808854859371733261",
    source: "twitter",
  },
  {
    id: 124,
    title: "Figma Variable & Animation #2",
    img: "variable-animation-2.png",
    date: "13 Jul, 2024",
    description: `2 hours long stream about working with variable to create complex interaction and animation.`,
    author: "realvjy",
    tags: ["figma", "video"],
    view: 51000,
    hidden: false,
    category: "figma",
    url: "https://www.youtube.com/watch?v=aNeSiu_HZCM",
    source: "youtube",
  },

  {
    id: 127,
    title: "Shiny Crystal",
    img: "crystal.jpeg",
    date: "17 Jul, 2024",
    description: `Let's create a cool, shiny crystal in a few steps Figma`,
    author: "realvjy",
    tags: ["figma", "any"],
    view: 51000,
    hidden: false,
    category: "figma",
    url: "https://x.com/realvjy/status/1813550684811497929",
    source: "twitter",
  },
  {
    id: 133,
    title: "Figma Advance Autolayout #3",
    img: "autolayout-live.png",
    date: "9 Aug, 2024",
    description: `2 hours long stream to create complex layout using autolayout. Created head rig.`,
    author: "realvjy",
    tags: ["figma", "video"],
    view: 51000,
    hidden: false,
    category: "figma",
    url: "https://www.youtube.com/watch?v=Uumnbu9C7s4",
    source: "youtube",
  },
  {
    id: 135,
    title: "Behind the scene of Figma Slides",
    img: "slides-figma-2.gif",
    date: "31 Jul, 2024",
    description: `Creation of figma slide using components`,
    author: "realvjy",
    tags: ["figma"],
    view: 51000,
    hidden: false,
    category: "figma",
    url: "https://vjy.me/figma",
    source: "vjy.me",
  },
  {
    id: 136,
    title: "Shiny Star",
    img: "shiny-star.png",
    date: "21 Aug, 2024",
    description: `Let's quickly create stylized and shiny star @figma ⭐️`,
    author: "realvjy",
    tags: ["figma", "any"],
    view: 51000,
    hidden: false,
    category: "figma",
    url: "https://x.com/realvjy/status/1826234647027847430",
    source: "twitter",
  },
  {
    id: 137,
    title: "Create a Figma Plugin #4",
    img: "create-a-figma.png",
    date: "23 Aug, 2024",
    description: `2 hours plus long stream to create a figma plugin from basic to advance.`,
    author: "realvjy",
    tags: ["figma", "video", "dev"],
    view: 51000,
    hidden: false,
    category: "figma",
    url: "https://www.youtube.com/watch?v=w4i7Exsx9H8",
    source: "youtube",
  },
];
