export type tutsDataType = {
  title: string;
  id: number;
  img: string;
  author: string;
  category: string;
  tags: string[];
  source: string;
  view: number;
  featured?: false;
  hidden?: false;
  description?: string;
  url: string;
  date: string;
};

// see public folder for thumbnail and logos
// TODO: automate fetching downloads
export const tutsData: tutsDataType[] = [
  {
    id: 10,
    title: "Halftone Effect",
    img: "halftone-effect.png",
    date: "18 Sep, 2022",
    description: `Yes, this is @figma . Simple halftone effects can be easily added to your photos and illustrations to give them a retro look. Another experimenting with @rogie NT plugin.`,
    author: "realvjy",
    tags: ["figma", "video"],
    view: 51000,
    hidden: false,
    category: "figma",
    url: "https://x.com/realvjy/status/1571479068851466240",
    source: "twitter",
  },
  {
    id: 11,
    title: "Engrave Effect",
    img: "engrave-effect.png",
    date: "27 Sep, 2022",
    description: `Experiment #9845 with @rogie NT plugin in @figma 😍. Creating the look of an old engraving halftone print was the challenge. Guess what, it's very simple to create by just using some wave patterns and blending modes.`,
    author: "realvjy",
    tags: ["figma", "video"],
    view: 51000,
    hidden: false,
    category: "figma",
    url: "https://x.com/realvjy/status/1574735646140162048",
    source: "twitter",
  },
  {
    id: 14,
    title: "Holographic Look",
    img: "holographic.png",
    date: "22 Sep, 2022",
    description: `Here's another experiment with @rogie NT plugin in @figma . I was trying to replicate the look of frosted glass using a special noise option hidden in the plugin. But, when I meshed up the colors together, it gave an interesting holographic look`,
    author: "realvjy",
    tags: ["figma", "video"],
    view: 51000,
    hidden: false,
    category: "figma",
    url: "https://x.com/realvjy/status/1572929708731559937",
    source: "twitter",
  },

  {
    id: 15,
    title: "Effect with NT plugin",
    img: "effect-with-nt.jpeg",
    date: "21 Nov, 2022",
    description: `Collection of effect using NT plugin`,
    author: "realvjy",
    tags: ["figma"],
    view: 51000,
    hidden: false,
    category: "figma",
    url: "https://www.figma.com/community/file/1176491955948168493/noise-and-effects-with-nt-plugin",
    source: "figma",
  },
  {
    id: 16,
    title: "Why I love Figma?",
    img: "love-figma.jpeg",
    date: "18 Oct, 2023",
    description: `Why I love @figma ? Every time I use Figma to create illustrations, you guys always ask me why. Here are a few points I would like to share in this thread 🧶. I also uploaded a time lapse to YouTube ▶️`,
    author: "realvjy",
    tags: ["figma", "sketch", "penpot"],
    view: 51000,
    hidden: false,
    category: "figma",
    url: "https://x.com/realvjy/status/1582359449963966464",
    source: "twitter",
  },
  {
    id: 18,
    title: "A Cool Loader",
    img: "cool-loader.jpeg",
    date: "6 Jan, 2023",
    description: `Small tips for creating this cool loader quickly in figma`,
    author: "realvjy",
    tags: ["figma"],
    view: 51000,
    hidden: false,
    category: "figma",
    url: "https://x.com/realvjy/status/1611352724968452098",
    source: "twitter",
  },
  {
    id: 19,
    title: "Head Rig",
    img: "head-rig.png",
    date: "1 Nov, 2022",
    description: `Another fun experiment using @figma prototype. I made this small head rig last week. Creating this was lot of fun 😍. By using cavas as masks and combining with autolayout, I created this so quickly.`,
    author: "realvjy",
    tags: ["figma", "video"],
    view: 51000,
    hidden: false,
    category: "figma",
    url: "https://x.com/realvjy/status/1587420082036412417",
    source: "twitter",
  },
  {
    id: 20,
    title: "Figma Emoji",
    img: "figma-emoji.jpeg",
    date: "14 Nov, 20223",
    description: `I found that if you use drop shadow or inner shadow on any layer, the limit is 8. In spite of this, it is enough to make any shape like 3D. One secret shared below ☺️.`,
    author: "realvjy",
    tags: ["figma"],
    view: 51000,
    hidden: false,
    category: "figma",
    url: "https://x.com/realvjy/status/1592117127716417537",
    source: "twitter",
  },

  {
    id: 21,
    title: "Isometric City",
    img: "isometric-city.png",
    date: "4 Apr, 2023",
    description: `Creating an isometric city landscape by setting up isometric shapes as component in @figma . When I update the base component, the isometric shapes update smoothly😍. Here small demo...`,
    author: "realvjy",
    tags: ["figma", "video"],
    view: 51000,
    hidden: false,
    category: "figma",
    url: "https://x.com/realvjy/status/1643231924293443586",
    source: "twitter",
  },
  {
    id: 22,
    title: "Figma Gold",
    img: "figma-gold.jpeg",
    date: "16 Jun, 2023",
    description: `For creating metal, I always use layer blur instead of gradient. And here is a cheat sheet to create a cool-looking gold in @figma ✨`,
    author: "realvjy",
    tags: ["figma", "any"],
    view: 51000,
    hidden: false,
    category: "figma",
    url: "https://x.com/realvjy/status/1669672486559002624",
    source: "twitter",
  },
  {
    id: 23,
    title: "Smooth Gradient",
    img: "smooth-gradient.jpeg",
    date: "9 Dec, 2022",
    description: `Small tip about blending gradients in @figma with background blur. You can create cool iridescent gradients using it.`,
    author: "realvjy",
    tags: ["figma"],
    view: 51000,
    hidden: false,
    category: "figma",
    url: "https://x.com/realvjy/status/1601209853875458053",
    source: "twitter",
  },
  {
    id: 29,
    title: "Cool Loader using Figma Variable",
    img: "loader-figma-variable.png",
    date: "7 Jul, 2023",
    description: `Here quick @figma tutorials on how to create a functional loader with variable and conditions 🤩. Small video tutorials added. And get the code cheatsheet and more from here`,
    author: "realvjy",
    tags: ["figma", "video"],
    view: 51000,
    hidden: false,
    category: "figma",
    url: "https://x.com/realvjy/status/1677281849431793664",
    source: "twitter",
  },
  {
    id: 31,
    title: "Juice glass animation with figma Variable",
    img: "juice-glass.png",
    date: "19 June, 2023",
    description: `Another quick @figma tutorial to create this animation using variable and conditions 🥤.  Small video to create this included. And get the code cheatsheet shared below. ✨`,
    author: "realvjy",
    tags: ["figma", "video"],
    view: 51000,
    hidden: false,
    category: "figma",
    url: "https://x.com/realvjy/status/1681610818046107651",
    source: "twitter",
  },
  {
    id: 34,
    title: "Figma Variable Experiment to create Segment Control",
    img: "segment-control-variable.png",
    date: "27 Dec, 2023",
    description: `It’s @figma fun day - Here's a quick tutorial demo for smart use case of the new variable updates. Created a smart segment control button and it’s so intelligent. Also shared cheatsheet for all variables below.`,
    author: "realvjy",
    tags: ["figma", "video"],
    view: 51000,
    hidden: false,
    category: "figma",
    url: "https://x.com/realvjy/status/1733104300354646473",
    source: "twitter",
  },
  {
    id: 37,
    title: "Create Hex Grid",
    img: "hex-grid-cheatsheet.jpeg",
    date: "27 Dec, 2023",
    description: `I was creating a layout for a game idea and looking for an easier way to generate a hex grid in @figma . After experimenting, found the exact values and tricks using smart components and auto layout to solve it. Added a quick tutorial video and demo here. Enjoy 🤩`,
    author: "realvjy",
    tags: ["figma", "video"],
    view: 51000,
    hidden: false,
    category: "figma",
    url: "https://x.com/realvjy/status/1739973126270885973",
    source: "twitter",
  },
  {
    id: 41,
    title: "Juice glass animation with figma Variable",
    img: "juice-glass.png",
    date: "19 June, 2023",
    description: `Another quick @figma tutorial to create this animation using variable and conditions 🥤.  Small video to create this included. And get the code cheatsheet shared below. ✨`,
    author: "realvjy",
    tags: ["figma", "video"],
    view: 51000,
    hidden: false,
    category: "figma",
    url: "https://x.com/realvjy/status/1808854859371733261",
    source: "twitter",
  },
  {
    id: 65,
    title: "Moving Sphere",
    img: "moving-sphere.gif",
    date: "25 April, 2024",
    description: `Moving sphere experiment in @figma ✨`,
    author: "realvjy",
    tags: ["figma"],
    view: 51000,
    hidden: false,
    category: "figma",
    url: "https://x.com/realvjy/status/1783474209089319303",
    source: "twitter",
  },
  {
    id: 60,
    title: "Modular Illustration",
    img: "modular-ticket-illustration.gif",
    date: "14 May, 2024",
    description: `Quick experment and demo in @figma : A non-destructive workflow to create modular illustrations or design ✨`,
    author: "realvjy",
    tags: ["figma"],
    view: 51000,
    hidden: false,
    category: "figma",
    url: "https://x.com/realvjy/status/1790353490071507013",
    source: "twitter",
  },
  {
    id: 61,
    title: "Glow Effect",
    img: "glow-cheatsheet.gif",
    date: "24 June, 2024",
    description: `Steps to create glow effect in figma`,
    author: "realvjy",
    tags: ["figma", "any"],
    view: 51000,
    hidden: false,
    category: "figma",
    url: "https://x.com/realvjy/status/1805220290382717219",
    source: "twitter",
  },
  {
    id: 114,
    title: "Create Shiny Metal",
    img: "shiny-metal.jpeg",
    date: "12 May, 2024",
    description: `Let's qucikly create some realstic and shiny metal @figma✨`,
    author: "realvjy",
    tags: ["figma", "any"],
    view: 51000,
    hidden: false,
    category: "figma",
    url: "https://x.com/realvjy/status/1808854859371733261",
    source: "twitter",
  },
];
